### ISSUE TITLE
MAX 11 beta 1: Errores, mejoras, fallitos, bugs, etc que van saliendo de está primera beta (consultar ya la  #1037 donde se encuentra actualizada la RC1)

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1035]
# LISTADO de VERIFICACIÓN de errores:

* [ ] Actualizar todos los programas que están en repos de MAX, pero no en el de Ubuntu.
* [ ] Mirar los comentarios de Daniel en este mismo hilo.
* [x] **Autofirma** No funciona en web. Mirar  #1032 y los comentarios de José Miguel. Gran idea que **Autofirma** funcione en modo live para sacar del apuro a cualquiera.
* [x] **[EDITADO TRAS ACTUALIZAR]** **Sigue sin ser transparente**. En usuario alumno el dock no se ve transparente independientemente de si es la cajonera de Infantil y Primaria o la nueva que hemos integrado. Ver #983.
* [x] **OBS-studio**. Actualizar a la versión 26.1 porque incluye ya de serie cámara virtual 
* [x] **OBS-studio** Incluir en repos **Noisetorch** que es un micrófono virtual que todavía no va de serie. https://github.com/lawl/NoiseTorch/releases/tag/0.10.1 
* [x] **OBS-studio** Incluir en repos **OBS-captions-plugin** que permite subtitular en tiempo real. Crucial para **ACCESIBILIDAD** https://github.com/ratwithacompiler/OBS-captions-plugin/releases ver https://www.youtube.com/watch?v=Uuh_0X8dsLs

* [x] **[EDITADO TRAS ACTUALIZAR]** Cambiar el icono del menú inicio de la cuadrícula al icono de EducaMadrid nuevo. Igualmente en el dock. **Se ha cambiado en el panel pero no en el dock**
![educamadrid_boton](https://user-images.githubusercontent.com/6005738/110201793-420ee080-7e65-11eb-91cb-928ee1f03677.png)

* [x] **[FUNCIONA]** Shutter no funciona. Versión 1:0.95-max1 que no aparece en el listado de http://max.educa.madrid.org/max11/ Recordar que hay nueva versión en https://github.com/shutter-project/shutter/releases 
* [ ] De inicio no parecen las carpetas del directorio Carpeta Personal: Documentos, Imágenes, Vídeos, Música, Descargas. Aparecen después de... ¿¿?? el caso es que al principio no están y luego si. Pero en el caso de alumno no aparecen en ningún caso. Relacionado con El "home" de alumno/profesor no incluye las carpetas de serie como a Madrid. #984 (ver también  #1024)
* [x]  La app +Aplicaciones max-mate-welcome no funciona
* [x] **[EDITADO TRAS ACTUALIZAR]** ~~Falta scratux en el menú programación https://github.com/scratux/scratux~~ Aparece solo en el menú **Otras aplicaciones educativas**. Tiene que ir en menú **Programación** también. Y no funciona da este error 
![Captura de pantalla -2021-03-10 21-19-07](https://user-images.githubusercontent.com/6005738/110692936-30239980-81e7-11eb-8fe1-f627fb72f885.png)

* [x] Falla puntualmente el renderizado de la ventana de entrada. Esto lo arrastramos de hace tiempo.
![Captura de pantalla -2021-03-03 22-29-44](https://user-images.githubusercontent.com/6005738/109875075-3f976580-7c70-11eb-8d85-992bcbdb0693.png)

* [x] **[EDITADO TRAS ACTUALIZAR]** Sustituir Xournal por Xournal++ Ver #1029 **¡ojo! Ahora están las dos**. Eliminar Xournal de la iso y que vaya Xournal++ y que aparezca en el menú Oficina pero también en el de **Pizarra digital** como **Anotador de PDF Xournal++**
* [ ] Los marcadores de Firefox deben salir directamente importados en Chromium.
* [ ] Thunderbird preconfigurado para EducaMadrid con imap.educa.madrid.org   puerto 993   SSL/TLS   Contraseña normal y smtp01.educa.madrid.org Puerto 465 seguridad ssl/tls contraseña normal.
* [ ] Thunderbird  también en el dock que este también para que los profesores se puedan acostumbrar a ese gestor de correo-e. Si no se puede hacer lo descrito en el punto anterior y se incluye el configurador descrito en https://github.com/maxezek/trucosMAX en los servidores de EducaMadrid se lo ponemos muy fácil. Esta idea de ponerlo en el dock es de Luis Alonso y me parece muy buena idea.
 
* [ ] **CRÍTICO Araword de Arasuite no funciona correctamente** #1003 Esto lo arrastramos y esto tiene que funcionar bien. (ver también  #1024)
* [ ] Incluir el reemplazo de tipo de letra para Calibri y Cambria por Carlito y Caladea en libreoffice como en los MAX anteriores 
![Captura de pantalla -2021-03-07 18-45-17](https://user-images.githubusercontent.com/6005738/110249281-c3ee2f00-7f75-11eb-8e58-662cc595aae8.png)

* [ ] Incluir que el programa de correo de LO sea Thunderbird 
![Captura de pantalla -2021-03-07 18-57-02](https://user-images.githubusercontent.com/6005738/110249580-0d8b4980-7f77-11eb-8a69-0dc1e6888671.png)

* [x] En Openboard no se ven los colores del lápiz aunque luego funcionan 
![Captura de pantalla -2021-03-10 21-08-32](https://user-images.githubusercontent.com/6005738/110694219-a07eea80-81e8-11eb-8a6b-7296330e5622.png)

* [ ] Incluir en repos https://github.com/Bitbloq/QSSWeb2Board para poder usar BitBloq de BQ. El último fuente es https://github.com/Bitbloq/QSSWeb2Board/releases/tag/3.5.0 
* [x] Reportado por Victor Armendariz. 3 iconos repetidos en menú: Sistema/Preferencias, Sistema/Centro de control y Sistema/Preferencias/Aspecto y comportamiento. Para los dos últimos los iconos alternativos pueden ser: /usr/share/icons/ePapirus/64x64/categories/mateconf-editor.svg y /usr/share/icons/ePapirus/64x64/categories/lookswitcher.svg
* [ ]  Reportado por Victor Armendariz. 3 iconos repetidos en menú: Gráficos/gThumb, Gráficos/Shotwell y Gráficos/Visor de imágenes Ojo de Mate. Alternativos /usr/share/icons/ePapirus/64x64/categories/photolayouteditor.svg y /usr/share/icons/ePapirus/64x64/categories/portal.svg
* [ ] Reportado por Victor Armendariz. No aparece en menú Sistema/Administración/Administración de arranque que es el paquete startupmanager que sin embargo está instalado. ¿Paquete python 2.7? Ver si se puede incluir o directamente sustiturlo por **grub-customizer**
* [x] Reportado por José Angel Navarro. No funciona Educación/Música/MuseScore (editor de partituras) hay que cambiar el lanzador y  poner en mscore.desktop Exec=mscore3 %F o sustituirlo directamente en mscore3.desktop y añadir ahí en Categories Education; 
* [x] Reportado por José Angel Navarro. No funciona bien **exeLearning.** No abre los .elp de MAX 10 por alguna extraña razón. Pero en el sitio oficial ya han hecho paquete .deb oficial y funciona. Sustituir el actual por https://descargas.intef.es/cedec/exe_learning/2.5.1/intef-exe_2.5.1_all.deb
* [x] Reportado por José Miguel. Incluir de serie **blueman** para dispositivos bluetooth. Ahora con tanta videollamada y uso de altavoces  y otros gadgets parace que merece la pena.
* [x] Reportado por Amadeo Mora. Mientras se instala aparece que llevamos Filezilla de serie y ya no es así. Retocar el instalador. 
* [ ] Incluir en caja la extensión de compresión de PDF. Ver https://github.com/maxezek/optimizarPDF La mejor opción creo que es https://github.com/maxezek/optimizarPDF#versi%C3%B3n-como-elemento-del-men%C3%BA-contextual-en-caja. La versión de escritorio de https://github.com/maxezek/optimizarPDF#versi%C3%B3n-lista-de-escritorio funciona en MAX 10 pero no en MAX 11.
* [ ] Problema con **SAMBA** descrito por Manuel Galvéz: 

Desde Caja normalmente con Control+L escribo:

ftp://(ip servidor) o smb://(ip servidor) y conecta con uno u otro protocolo.

En MAX11 smb no conecta.

He probado "Menú->Lugares->Conectarse al servidor..." con el mismo resultado.

Y en terminal con "mount.cifs" y lo mismo.

SOLUCIÓN: He conseguido conectar haciendo lo siguiente.

Editar /etc/samba/smb.conf archivo (se necesitan permisos de root)

en la [global] sección, agregar la siguiente línea.

client min protocol = NT1

Tras ello se reinicia el servicio.

sudo service smbd restart

* [x] Error en el prompt de MAX 11. También Manuel Gálvez:  en MAX11 live al abrir una terminal en el promp aparece max10.
 

* [ ] Continuará

**Comment by maxezek** [comment]
Seguimos con problemas con el dock en alumno.

* [ ] **[EDITADO TRAS ACTUALIZAR]** **Sigue sin ser transparente**. En usuario alumno el dock no se ve transparente independientemente de si es la cajonera de Infantil y Primaria o la nueva que hemos integrado. Ver #983.

**Comment by DaniMAdridlinuX** [comment]
- [ ] Que ya venga por defecto configurado en Owncloud el servidor de EducaMadrid "cloud.educa.madrid.org" aunque luego pueda cambiarlo el usuario.

**Comment by DaniMAdridlinuX** [comment]
Ahora mismo solo tenemos una página de MAX y todos los enlaces que iban a otra web tienen que ir a la nueva. Por ejemplo en la página de inicio del navegador modificaandoo lo siguiente:

Donde pone : "Complete su instalación de MAX con las sugerencias recopiladas en +Aplicaciones"

> 
![Área de trabajo 1_001](https://user-images.githubusercontent.com/75364104/112132418-e49bc300-8bca-11eb-8361-0eaddb4c80b6.png)

**Comment by maxezek** [comment]
Lo he cambiado en https://github.com/max-linux/max-desktop/blob/master/max-ubufox/content/startpage.html

¿Hay que cambiar más?

**Comment by DaniMAdridlinuX** [comment]
Esta es la imagen con el nuevo logo de EducaMadrid para la pantalla de entrada

![maxgdm_neutro_DIC2020_ABES](https://user-images.githubusercontent.com/75364104/115219941-47b84100-a108-11eb-9435-71d85f23f4b1.png)

**Comment by DaniMAdridlinuX** [comment]
> Esta es la imagen con el nuevo logo de EducaMadrid para la pantalla de entrada
> 
> ![maxgdm_neutro_DIC2020_ABES](https://user-images.githubusercontent.com/75364104/115219941-47b84100-a108-11eb-9435-71d85f23f4b1.png)

Esta imagen se puede usar en los fondos que tienen el icono desactualizado como por ejemplo:

![MAXgrubMAL](https://user-images.githubusercontent.com/75364104/118017856-5edcfe00-b357-11eb-9be0-40e8032009e7.png)

![pantallaInstalarprobar](https://user-images.githubusercontent.com/75364104/118017864-62708500-b357-11eb-9310-98d8c9f54c2c.png)

![UsuariosMAL](https://user-images.githubusercontent.com/75364104/118017872-64d2df00-b357-11eb-8a07-aba3c3ae1c52.png)

**Comment by DaniMAdridlinuX** [comment]
Durante el proceso de instalación aparecen ventanas con información desactualizada. Voy poniendo el pantallazo de lo que se ve y lo que debería verse:

![proceso instalación](https://user-images.githubusercontent.com/75364104/118018248-d90d8280-b357-11eb-9db6-9233a58536f0.png)

En esta hay que cambiar la imageny el texto. La imagen usando esta:


![instalacion_max11_DIC2020_ABES](https://user-images.githubusercontent.com/75364104/118018310-e9bdf880-b357-11eb-93df-ecaeda60dea3.png)

Y en el texto sustituyendo DVD por USB ya que la nueva versión solo vendrá en USB de manera oficial.

**Comment by DaniMAdridlinuX** [comment]
En esta imagen cambiar el logo de EducaMadrid por el nuevo y en vez de Consejría de Educación e investigación debe poner Consejería de Educación y Juventud

![Uploading BienvenidoMAL.png…]()

**Comment by DaniMAdridlinuX** [comment]
En esta actualizar el Icono de EducaMadrid

![AplicacionesMAL](https://user-images.githubusercontent.com/75364104/118018828-939d8500-b358-11eb-9e17-f26ff4ff1403.png)

**Comment by DaniMAdridlinuX** [comment]
En esta quitar el segundo párrafo y actualizarlo con lo siguiente:

Con MAX podrá realizar sus videoconferencias en Jitsi, tanto dentro como fuera de las AulasVirtuales. También permite el uso de Webex integrado en nuestras Aulas Virtuales.

![ConectadoMAL](https://user-images.githubusercontent.com/75364104/118019126-ebd48700-b358-11eb-8731-5a052fecf026.png)

**Comment by DaniMAdridlinuX** [comment]
En esta incluir en el primer párrafo USB. "...desde la WEB, USB, CD y DVD."
En el segundo párrafo quitar la frase "Conecte un reporductor MP3 para empezar a sincronizar su colección de música, o introduzca un CD para copiar canciones a su equipo."
En el tercer párrafo redactarlo de la siguiente manera: "El reproductor de vídeo VLC le permite visualizar cualquier vídeo en local o en la red. MAX también está preparado para reproducir cualquier medio incluido en la Mediateca de EducaMadrid. Visítela en https://mediateca.educa.madrid.org"

![EntretenimientoMAL](https://user-images.githubusercontent.com/75364104/118019722-98af0400-b359-11eb-98b0-f28fd6d0dfed.png)

**Comment by DaniMAdridlinuX** [comment]
En el siguiente dejar el primer párrafo solo con la primera frase: "MAX incorpora el aclamado Navegador Firefox en su última versión." 

![NavegueMAL](https://user-images.githubusercontent.com/75364104/118019916-d318a100-b359-11eb-9715-a437de08b987.png)

**Comment by DaniMAdridlinuX** [comment]
Este no se modifica:

![OfimaticaBIEN](https://user-images.githubusercontent.com/75364104/118019978-e62b7100-b359-11eb-899a-ba05eb1e8360.png)

**Comment by DaniMAdridlinuX** [comment]
En esta cambiar la imagen del pájaro por la que viene en este enlace: `https://www.pngegg.com/es/png-cytgc`

![VidaDigitalMAL](https://user-images.githubusercontent.com/75364104/118020607-8d100d00-b35a-11eb-8726-5df794a7682b.png)

**Comment by DaniMAdridlinuX** [comment]
Faltan dos pantallas aún por cambiar: la de "Consigue más aplicaciones" y la de "Usar en la nube" En esas hay que poner el icono nuevo de EducaMadrid

![logoeducamadrid](https://user-images.githubusercontent.com/75364104/118020834-dbbda700-b35a-11eb-9a50-b4ad4b0354bd.png)

**Comment by maxezek** [comment]
Daniel, creo que esto si podemos cambiarlo nosotros poco a poco.

Está en [https://github.com/max-linux/max-desktop/tree/master/ubiquity-slideshow-max/slideshows/ubuntu/slides](https://github.com/max-linux/max-desktop/tree/master/ubiquity-slideshow-max/slideshows/ubuntu/slides
)

Esto es lo que no he encontrado de max-mate-welcome pero para las diapositivas del instalador sí que podemos meter mano

**Comment by maxezek** [comment]
Creo que he cambiado todas las "slides" del instalador. Hay que comprobarlo con más ojos

**Comment by maxezek** [comment]
También he cambiado ya las imágenes de pantalla de entrada (gdm) [https://user-images.githubusercontent.com/75364104/115219941-47b84100-a108-11eb-9435-71d85f23f4b1.png](https://user-images.githubusercontent.com/75364104/115219941-47b84100-a108-11eb-9435-71d85f23f4b1.png)

[https://github.com/max-linux/max-desktop/tree/master/max-artwork/art/gdm/Max](https://github.com/max-linux/max-desktop/tree/master/max-artwork/art/gdm/Max)

**Comment by maxezek** [comment]
Cambiada también la imagen del grub https://user-images.githubusercontent.com/75364104/118017856-5edcfe00-b357-11eb-9be0-40e8032009e7.png

[https://github.com/max-linux/max-desktop/tree/master/max-artwork/art/grub](https://github.com/max-linux/max-desktop/tree/master/max-artwork/art/grub)

**Comment by DaniMAdridlinuX** [comment]
Actualizado y comprobados todos los cambios en las slides del proceso de instalación de MAX: https://github.com/max-linux/max-desktop/tree/master/ubiquity-slideshow-max/slideshows/ubuntu/slides

**Comment by DaniMAdridlinuX** [comment]
No encuentro esta imagen para actualizarla: https://github.com/max-linux/max-desktop/issues/1035#issuecomment-839959600

**Comment by maxezek** [comment]
Cambiada también  max-desktop/plymouth-max/themes/max-logo/logo_educa.png 

https://github.com/max-linux/max-desktop/blob/master/plymouth-max/themes/max-logo/logo_educa.png

Y en otra versión:

https://github.com/max-linux/max-desktop/blob/master/plymouth-max/themes/max-logo/logo_educav2.png

Creo que influyen en las de arranque pero no estoy seguro.

**Comment by victoramdz** [comment]
scratux....

los repositorios  oficiales  no estan fucionando pero el  enlace alternativo al .deb si está operativo, lo he probado en una max11 limpia y fuciona.  Version 1.4.1
https://github.com/scratux/scratux/wiki/Installing-for-Ubuntu,-Linux-Mint-and-derivates

**Comment by maxezek** [comment]
> No encuentro esta imagen para actualizarla: [#1035 (comment)](https://github.com/max-linux/max-desktop/issues/1035#issuecomment-839959600)

https://github.com/max-linux/max-desktop/blob/master/ubiquity-frontend-max/usr/share/ubiquity/pixmaps/max/logo.png

**Comment by maxezek** [comment]
@victoramdz ahora está en https://github.com/max-linux/max-desktop/blob/master/max-artwork/art/gdm/Max/maxgdm.png y tiene el logo antiguo de EducaMadrid. Creo que la había cambiado a esta:

https://user-images.githubusercontent.com/75364104/115219941-47b84100-a108-11eb-9435-71d85f23f4b1.png
